### ISSUE TITLE
When can we expect the next update?

### ISSUE THREAD

**Issue by Yashko** [kaxap/arl#13]
`It is updated every now and then, but generally every 3-4 weeks.`

Since it's been three months already ;(

**Comment by kaxap** [comment]
Sorry, I was completely out of the loop with the whole quarantine thing. Will try to update ASAP.

**Comment by kaxap** [comment]
@Yashko I have updated the repository. Thanks for the remainder!

**Comment by Yashko** [comment]
@kaxap Thank you!
