### ISSUE TITLE
Vue.js absence in "README-JS.md"

### ISSUE THREAD

**Issue by Yashko** [kaxap/arl#14]
Vue.js repository (https://github.com/vuejs/vue) have over 160k stars but its not in the list. Why?

UPD: I can see Vue.js in the "README-Node.md" list, and "react" as well. But the same "react" repository listed inside of "README-JS.md". How come?

**Comment by kaxap** [comment]
hmm, seems like "JS" and "JavaScript" queries are treated differently by GitHub. Thanks for the report, I'll fix it ASAP.

**Comment by kaxap** [comment]
[Fixed](https://github.com/kaxap/arl/blob/master/README-JS.md)

**Comment by kaxap** [comment]
[Fixed](https://github.com/kaxap/arl/blob/master/README-JS.md)

**Comment by Yashko** [comment]
Thank you
