### ISSUE TITLE
Why there isn't JavaScript?

### ISSUE THREAD

**Issue by Mr-dang** [kaxap/arl#2]
TypeScript and CoffeScript are both form JavaScript, why there are both them and not JavaScript?

**Comment by kaxap** [comment]
There is [NodeJS](https://github.com/kaxap/arl/blob/master/README-Node.md) as well. So there are 3 subtypes of JS in the list.

**Comment by kaxap** [comment]
@Mr-dang 
I'll add JS in the next update

**Comment by kaxap** [comment]
[Added](https://github.com/kaxap/arl/blob/master/README-JS.md)
